type Movie {
  id: ID!
  name: String!
  genres: [Genre]!
  score: Float!
  wikiURL: String
  description: String
}

type Genre {
  id: ID!
  name: String!
}

type Query {
  hello: String
  getFirstPopularMovie: Movie
  searchMovie(keyword: String!, wikiToggle: Boolean): [Movie]
}
